### ISSUE TITLE
energy transfer occurs between vacuum and anything else

### ISSUE THREAD

**Issue by InterestingGuyNo1** [qazox/altboxels#2]
hi. vacuum has real temperature, made air cold. it shouldn't happen, right? ??? made the vacuum hot, not possible right?

vacuum should always be at (vacuum temperature) and nothing else. It doesn't make sense

**Comment by qazox** [comment]
Fixed in commit https://github.com/qazox/altboxels/commit/bb5e0bebdaff5712c191e23c857be95aaa2b7ac3
